main: net.horizonsend.ion.server.IonServer

version: unspecified
api-version: 1.19
load: POSTWORLD

name: Ion
website: https://horizonsend.net
author: Peter-Crawley
authors:
  - MicleBrick
  - Sciath
  - Gutin1 (Gutin)
  - quinnbuskus (liluzivirt)
  - trainb0y
  - ItsAlreadyGold
  - PiggleMcDiggle (DoctorXeno)
  - Vandrayk
  - EmeraldBlade (EmeraldsGaming)

depend:
  - WorldEdit

softdepend:
  - Citizens
  - DiscordSRV
  - LuckPerms
  - Vault
  - dynmap